<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseWindowsForms>true</UseWindowsForms>
    <Authors>Yodadude2003</Authors>
    <Company>Chosen Few Software</Company>
    <PackageId>ModLoader</PackageId>
    <Version>1.14</Version>
    <ApplicationIcon>Logo\Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\*" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Logo\Icon.ico" />
    <None Remove="Logo\Translucent.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Logo\Icon.ico" />
    <EmbeddedResource Include="Logo\Translucent.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ModLoader.Core\ModLoader.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>