//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModLoader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        public static Settings Default {
            get {
                return ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.55")]
        public double LoaderMainPanelSplit {
            get {
                return ((double)(this["LoaderMainPanelSplit"]));
            }
            set {
                this["LoaderMainPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double LoaderTopPanelSplit {
            get {
                return ((double)(this["LoaderTopPanelSplit"]));
            }
            set {
                this["LoaderTopPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.35")]
        public double LoaderBottomPanelSplit {
            get {
                return ((double)(this["LoaderBottomPanelSplit"]));
            }
            set {
                this["LoaderBottomPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double LoaderPacksPanelSplit {
            get {
                return ((double)(this["LoaderPacksPanelSplit"]));
            }
            set {
                this["LoaderPacksPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double LoaderDetailsPanelSplit {
            get {
                return ((double)(this["LoaderDetailsPanelSplit"]));
            }
            set {
                this["LoaderDetailsPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double LoaderOtherPanelSplit {
            get {
                return ((double)(this["LoaderOtherPanelSplit"]));
            }
            set {
                this["LoaderOtherPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public double LoaderPropActionPanelSplit {
            get {
                return ((double)(this["LoaderPropActionPanelSplit"]));
            }
            set {
                this["LoaderPropActionPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.45")]
        public double LoaderAppWidth {
            get {
                return ((double)(this["LoaderAppWidth"]));
            }
            set {
                this["LoaderAppWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double LoaderAppHeight {
            get {
                return ((double)(this["LoaderAppHeight"]));
            }
            set {
                this["LoaderAppHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double MergerMainPanelSplit {
            get {
                return ((double)(this["MergerMainPanelSplit"]));
            }
            set {
                this["MergerMainPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double MergerTopPanelSplit {
            get {
                return ((double)(this["MergerTopPanelSplit"]));
            }
            set {
                this["MergerTopPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double MergerBottomPanelSplit {
            get {
                return ((double)(this["MergerBottomPanelSplit"]));
            }
            set {
                this["MergerBottomPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double MergerLeftPanelSplit {
            get {
                return ((double)(this["MergerLeftPanelSplit"]));
            }
            set {
                this["MergerLeftPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double MergerAppWidth {
            get {
                return ((double)(this["MergerAppWidth"]));
            }
            set {
                this["MergerAppWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double MergerAppHeight {
            get {
                return ((double)(this["MergerAppHeight"]));
            }
            set {
                this["MergerAppHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double UpdaterMainPanelSplit {
            get {
                return ((double)(this["UpdaterMainPanelSplit"]));
            }
            set {
                this["UpdaterMainPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double UpdaterLeftPanelSplit {
            get {
                return ((double)(this["UpdaterLeftPanelSplit"]));
            }
            set {
                this["UpdaterLeftPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.4")]
        public double UpdaterTopPanelSplit {
            get {
                return ((double)(this["UpdaterTopPanelSplit"]));
            }
            set {
                this["UpdaterTopPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double UpdaterDetailsPanelSplit {
            get {
                return ((double)(this["UpdaterDetailsPanelSplit"]));
            }
            set {
                this["UpdaterDetailsPanelSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double UpdaterAppWidth {
            get {
                return ((double)(this["UpdaterAppWidth"]));
            }
            set {
                this["UpdaterAppWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double UpdaterAppHeight {
            get {
                return ((double)(this["UpdaterAppHeight"]));
            }
            set {
                this["UpdaterAppHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoaderMaximized {
            get {
                return ((bool)(this["LoaderMaximized"]));
            }
            set {
                this["LoaderMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MergerMaximized {
            get {
                return ((bool)(this["MergerMaximized"]));
            }
            set {
                this["MergerMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdaterMaximized {
            get {
                return ((bool)(this["UpdaterMaximized"]));
            }
            set {
                this["UpdaterMaximized"] = value;
            }
        }
    }
}
