<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Product>ModLoader</Product>
    <Company>Chosen Few Software</Company>
    <Authors>Yodadude2003</Authors>
    <Version>1.13</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="33.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

</Project>
