<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Product>ModLoader</Product>
		<Company>Chosen Few Software</Company>
		<Authors>IsaMorphic</Authors>
		<Version>1.20.3</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentFTP" Version="55.0.0" />
	</ItemGroup>

</Project>
